### ISSUE TITLE
no angery birbs

### ISSUE THREAD

**Issue by armcburney** [davepagurek/ForTheBirds#1]
needs angery birb game

![image](https://cloud.githubusercontent.com/assets/8942499/19018528/f1ae1584-8832-11e6-862b-433c33ccc301.png)

**Comment by davepagurek** [comment]
it is now ur job to agnry burb

**Comment by armcburney** [comment]
angerey :angry: :bird:
<img width="1011" alt="screen shot 2016-10-02 at 12 02 01 am" src="https://cloud.githubusercontent.com/assets/8942499/19018534/87ba669a-8833-11e6-9012-73ab71acb751.png">

**Comment by davepagurek** [comment]
:'(
